name: air_quality_apps
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.6 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  dropdown_search: 5.0.6
  dio: 5.3.2
  google_fonts: ^5.1.0
  percent_indicator: 4.2.3
  location_picker_flutter_map: 1.2.2
  location: ^5.0.0
  http: 1.1.0
  animated_bottom_navigation_bar: 1.2.0
  loading_animation_widget: 1.2.0+4
  flutter: 
    sdk: flutter
  fl_chart: ^0.63.0
  another_flutter_splash_screen: ^1.1.5
  animated_splash_screen: ^1.3.0
  draggable_bottom_sheet: ^1.0.2
  expandable_bottom_sheet: ^1.1.1+1
  simple_progress_indicators: ^0.2.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets:
  - assets/icons/
  uses-material-design: true

